/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertAdult: typeof import('./src/components/AlertAdult.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    ButtonDefault: typeof import('./src/components/ButtonDefault.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    CatalogCarouselTop: typeof import('./src/components/CatalogCarouselTop.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FiltersCatalog: typeof import('./src/components/FiltersCatalog.vue')['default']
    FooterDefault: typeof import('./src/components/FooterDefault.vue')['default']
    HomeButton: typeof import('./src/components/HomeButton.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
